### PR TITLE
Add 32-bit Windows installers for Python 3.5 and 3.6

### PR DESCRIPTION
**Pull request by benfulton**

### CODE REVIEW

**Comment by peterjc** [comment]
Lovely, thank you! For future reference, the checksums are:

```
$ md5sum biopython-1.69.*
18ad299569eea79febf4641cce840db0  biopython-1.69.tar.gz
1acfa83d7340d82e248261f8344038be  biopython-1.69.win32-py2.7.exe
ff38a7286b455156619c8c2c4cb45a0e  biopython-1.69.win32-py2.7.msi
e03809050cd862226299ba4285b25615  biopython-1.69.win32-py3.3.exe
f8605d2e76e60353c776f69991067e07  biopython-1.69.win32-py3.3.msi
6bc7d291b7482f194f66a91d3eb89cb6  biopython-1.69.win32-py3.4.exe
0bc8e39ca0c3127b531f1998c91c7233  biopython-1.69.win32-py3.4.msi
0944a254c079869c481c13ac3bfa6c53  biopython-1.69.win32-py3.5.exe
567ba8c2b5e069cbcda5b13b558e4b1e  biopython-1.69.win32-py3.5.msi
48549d7083f1dcd37f73acfdbb30c100  biopython-1.69.win32-py3.6.exe
d3e02e227b6db736bc15f3ce4a08c149  biopython-1.69.win32-py3.6.msi
a134c5b8e35d6515ca4f9e663000bcb3  biopython-1.69.zip
```

And:

```
$ shasum -a 256 biopython-1.69.*
169ffa90c3d3ec5678c7a5c99501c0cfeb54c40ca51a619ce6cee5026d3403eb  biopython-1.69.tar.gz
6520ac092f52fd35b48d12c5f264d78c4cd20ede841a4755b73376184c1f9c83  biopython-1.69.win32-py2.7.exe
505aa27537f358129d096c1cb5b761108c6200a11483d25ad83188b11089b45c  biopython-1.69.win32-py2.7.msi
11a5a04da0d8830789d53fed7d631f5a8a6d3926869241d212265b7b9889b987  biopython-1.69.win32-py3.3.exe
7e3e764236e29f01fe3b346878801ee9f1166269e4ac557d88201e2f1cd85949  biopython-1.69.win32-py3.3.msi
c9ee5594e5f865fbf4871be8661e4be559dcb599c64e7fa4922e55b771aab249  biopython-1.69.win32-py3.4.exe
8426e2b548e594d63bfa7584f39513ee906d2de32037c900af9b6625318e051c  biopython-1.69.win32-py3.4.msi
3025f12b7f8cf81b25823223dc17830d4e0eeda8095e59177069d44fa2be9d32  biopython-1.69.win32-py3.5.exe
853eb6b75ca84ba703e0c8873d673b49f1580b5b1b9372105fbf9735153ad0dd  biopython-1.69.win32-py3.5.msi
7f11960168e335c1581de2e4a90bef905c92e08d42c67482f25a522db5d7b702  biopython-1.69.win32-py3.6.exe
4cac457773f251c511ede520f3e8701d8f00e22524103e03d0d1f69a040f95bf  biopython-1.69.win32-py3.6.msi
e71ae4c5ba996cbe01002d55d877bf5eafa053c116012d7ace489dfc41959e05  biopython-1.69.zip
```

**Comment by peterjc** [comment]
Also which version of NumPy did you have installed for Python 3.5 and 3.6?

**Comment by peterjc** [comment]
P.S. Any idea why the Python 3.5 files are about 3.5MB? I've noticed a similar bloat and it seems to happen when not building from a clear repository, but haven't ever solved why.

**Comment by benfulton** [comment]
Numpy was version 1.11.1 for 3.5 and 1.11.3 for 3.6. No, I don't have a guess on the file sizes :)

**Comment by peterjc** [comment]
Thanks, this reminded me to add the links to the download page,

https://github.com/biopython/biopython.github.io/commit/0639631cd0a37d76c247929491b20ad206610aa8

**Pull request merged**
