### PR TITLE
add tutorial PDFs for all previous versions of Biopython

### PR DESCRIPTION
**Pull request by mdehoon**
This PR adds the PDFs for the Biopython tutorial for each previous Biopython release. The Biopython release number is included in the file name of the PDF, e.g. `Tutorial-1.78.pdf`. Including these PDFs in DIST allows us to point users to the relevant Biopython documentation for the Biopython version they are using.

### CODE REVIEW

**Comment by peterjc** [comment]
Good idea to have this online, but wouldn't in folder ``docs/tutorial/`` next to the live tutorial make more sense?

**Comment by peterjc** [comment]
Did you adjust the date for the last few releases? See https://github.com/biopython/biopython/commit/181c85d3777a49d8ac8178b093484dbb4a48a174 which added the use of ``\today`` replacing a hard coded date?

**Comment by mdehoon** [comment]
> Did you adjust the date for the last few releases? See [biopython/biopython@181c85d](https://github.com/biopython/biopython/commit/181c85d3777a49d8ac8178b093484dbb4a48a174) which added the use of `\today` replacing a hard coded date?

For a few of the oldest releases, I regenerated the PDF by running pdflatex. But otherwise I simply took the PDF from the source distribution without regenerating it.

**Comment by peterjc** [comment]
Ah - extracting them from the tar-ball does sound easier!

**Review by peterjc — APPROVED** [review]
Squash-and-merge?

**Comment by mdehoon** [comment]
Thanks

**Comment by peterjc** [comment]
We forgot to update https://github.com/biopython/biopython.github.io/blob/master/wiki/Building_a_release.md accordingly...

**Pull request merged**
