### PR TITLE
Windows installers, MSI's and wheels for 1.70

### PR DESCRIPTION
**Pull request by benfulton**
64-bit versions for Python 2.7 and 3.6 

2.7 was built with Python 2.7.13 and numpy 1.11.3+mkl
3.6 was built with Python 3.6.1 and numpy 1.13.1+mkl 

Tests mostly passed, with one failure involving 64-bit code, I think:

Bio.Affy.CelFile.read_v4
Failed example:
    print(c.intensities.shape)
Expected:
    (5, 5)
Got:
    (5L, 5L)

More versions to come!

### CODE REVIEW

**Comment by peterjc** [comment]
Thanks Ben.

The ``5`` vs ``5L`` is going to be Python 2 specific as Python 3 unified int and long, so I'm not worried about that in terms of the current release - but it would we good to tweak the test to pass (or get skipped).

I'm probably not going to use your wheel, in favour of a full set via https://github.com/biopython/biopython-wheels as proposed at http://mailman.open-bio.org/pipermail/biopython-dev/2017-July/021817.html

I think potentially that system can be expanded to build the MSI and EXE installers too for future releases - the more we can automate here the better.

Peter

**Comment by peterjc** [comment]
How confident are you about the portability of the 64-bit Windows installers? Evidently at some point NumPy settled on an approach and now releases official binaries - so we should be OK as long as it is compiled against them...

i.e. We won't need to point people at  Christoph Gohlke's set (which I see he has already updated for  Biopython 1.70)?

**Comment by peterjc** [comment]
I could reproduce the doctest failure under AppVeyor as part of testing the wheel process:

https://ci.appveyor.com/project/biopython/biopython-wheels/build/1.0.10/job/ow4ualic5sha1fcy

```
======================================================================
FAIL: read_v4 (Bio.Affy.CelFile)
Doctest: Bio.Affy.CelFile.read_v4
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda-x64\envs\test_env\lib\doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for Bio.Affy.CelFile.read_v4
  File "C:\projects\biopython-wheels\biopython\build\lib.win-amd64-2.7\Bio\Affy\CelFile.py", line 137, in read_v4
----------------------------------------------------------------------
File "C:\projects\biopython-wheels\biopython\build\lib.win-amd64-2.7\Bio\Affy\CelFile.py", line 154, in Bio.Affy.CelFile.read_v4
Failed example:
    print(c.intensities.shape)
Expected:
    (5, 5)
Got:
    (5L, 5L)
----------------------------------------------------------------------
Ran 274 tests in 134.514 seconds
```

This was using 64-bit Python 2.7 via miniconda.

Currently the main repository's AppVeyor only covers:

* 32-bit Python 2.7
* 32-bit Python 3.6
* 64-bit Python 3.6

It looks like we should at least add 64-bit Python 2.7 there...

**Comment by peterjc** [comment]
I've logged the ``Bio.Affy.CelFile`` doctest as https://github.com/biopython/biopython/issues/1317 with work-around for the wheels in https://github.com/biopython/biopython-wheels/commit/5c83aa850fbd5a911f5227fa0517c67636ad80ab

And I found another one, phenotype doctests in Tutorial on 32-bit Windows Python 3.5, logged as https://github.com/biopython/biopython/issues/1316 with brute-force work-around for the wheels in https://github.com/biopython/biopython-wheels/commit/ef4c4838a26d6e8f59d4f9efbec313e658269ce9

**Comment by benfulton** [comment]
I'm not sure what you're asking about 64-bit portability? I'm confident it would work with currently supported 64-bit Windows versions (7, 8, 10, etc.)

**Comment by peterjc** [comment]
In years gone by, you had to be careful about C library/linking which could break if for example NumPy was compiled under one system, but Biopython on another.

**Comment by peterjc** [comment]
Hi Ben,

I hope to have the automated wheels for Biopython 1.70 from https://github.com/biopython/biopython-wheels on PyPI later this week, cross reference https://github.com/biopython/biopython/issues/1296

I'd prefer to avoid ever releasing a 64-bit Windows installer in favour of using wheels. See also https://github.com/matthew-brett/multibuild/issues/39 and note http://www.lfd.uci.edu/~gohlke/pythonlibs/ also uses wheels now.

So, having thought about this, I'd rather not share the files you've prepared so far on this pull request. Sorry about that.

However, since we've traditionally provided 32-bit Windows installers, we could do them for this one final release - if you'd like to?

Peter

**Comment by peterjc** [comment]
Belated closing this - we didn't have any calls to provide Windows installers that I noticed, so the compiled wheels seem to be working nicely.

**Pull request closed without merging**
