### PR TITLE
Redirect Biopython 1.75 epydoc pages to Sphinx equivalents

### LINKED ISSUE #2905: Adding redirects to old epydoc API documentation
See #906, we used to generate the API documentation at http://biopython.org/DIST/docs/api/ using epydoc (last updated for Biopython 1.75), but now generate it using Sphinx here https://biopython.org/docs/dev/api/ or https://biopython.org/docs/1.77/api/ etc (version specific URLs)

This issue is for adding redirects, probably to the https://biopython.org/docs/1.75/api/  version to avoid issues with things which have since been deleted? See also discussion on https://github.com/biopython/biopython/issues/2904

Probably adding an HTML snippet with JavaScript and a human readable fallback to the start of each page would be neatest - this would need to be automated! It might be possible using epydoc if that has a header/footer setting we can use?

The changes would be here https://github.com/biopython/DIST/tree/gh-pages/docs/api (on a separate git repository, but we deliberately turned off the issue tracker there)

### PR DESCRIPTION
**Pull request by peterjc**
Fixes https://github.com/biopython/biopython/issues/2905

### CODE REVIEW

**Comment by peterjc** [comment]
In some cases 1.75 didn't have C module docstrings, and thus did not appear in the Sphinx docs e.g. https://github.com/biopython/biopython/issues/2756

Might have been able to redirect to a later version, but then some modules have been removed (like `Bio.trie`) so sticking with 1.75 seemed simplest.

**Comment by peterjc** [comment]
@MarkusPiotrowski could you give this a quick sanity check please?

**Comment by MarkusPiotrowski** [comment]
I checked a number of pages and the re-direct was always working smoothly.

Some suggestions:

- The doc start page of 1.75 (and for earlier sphinx-generated releases) should be updated because it contains a link to the old epydoc pages: https://biopython.org/docs/1.75/api/
- I feel uncomfortable that the re-directed user may not be aware that he is looking on an 'outdated' documentation. In other 'read-the-docs'-like documentations I have often seen that on the sidebar they do not only display the version but also a link to the current version. Or possibly it was a header that warns about being on an older version? 
- Having also a 'dev' documentation, the sidebar could look like this: 1.75 | latest release | in development
  (with the corresponding links)
- In addition, I think clicking on the Biopython icon in the sidebar should redirect to the main biopython.org, not to the main doc site.

I haven't made myself familiar with how these pages are generated, so unfortunately I cannot help on this immediately.

**Comment by peterjc** [comment]
Shall we merge this as is then?

Follow on queries:

* I think 1.75 was the first release using Sphinx. Would you remove that link or just change the text above it somehow?
* Multiple versions of the (API) docs - yes, I agree - see https://github.com/biopython/biopython/issues/2906
* Same answer, switching between the docs for a past release, or the latest dev version https://biopython.org/docs/dev/api/ (which is updated automatically).
* Should be possible, I don't know how immediately. Do you want to open an issue on that?

(Updated to fix link)

**Comment by MarkusPiotrowski** [comment]
Yes, merge as it is, and then I open an issue in Biopython/docs for other stuff. 

The earliest Spinx release was 1.74 and I think it would suffice to remove the link to the dist pages.

**Comment by peterjc** [comment]
Indeed, https://biopython.org/docs/1.74/api/

**Pull request merged**
